language: python

python:
  - "3.4"

addons:
  postgresql: "9.4"

before_install:
    pip install codecov

after_success:
    codecov

before_script:
  - psql -c 'create database "cfdm-unit-test";' -U postgres
  - pip install -r requirements.txt

script: nosetests
