language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
env: SQLA_CONN="postgresql://:@/cfdm_test"
before_script:
  - psql -c 'create database cfdm_test;' -U postgres 
  - psql -f data/cfdm_test.pgdump.sql -U postgres
  - pip install -r webservices/requirements.txt
script: nosetests
